### ISSUE TITLE
API not up to date

### ISSUE THREAD

**Issue by GreenFlag31** [creacore-team/cbe2json#1]
Newly created companies (>2020 ?) are not listed in your API.

For exemple "0773.591.826" created in 2021, not found through your API.

This company exists : https://kbopub.economie.fgov.be/kbopub/zoeknummerform.html?nummer=0773.591.826&actionLu=Search

**Comment by Bruno361** [comment]
The data on the free plan has been updated, you should now find the CBE number you mentioned through the API.
